name: hk220  

services:
  nginx:
    image: nginx:latest
    container_name: nginx-service
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
      - ./ssl/www.docker-registry.asia.crt:/etc/nginx/ssl/www.docker-registry.asia.crt
      - ./ssl/www.docker-registry.asia.key:/etc/nginx/ssl/www.docker-registry.asia.key
    depends_on:
      - registry

  registry:
    container_name: docker-registry-v2
    image: registry:2
    restart: always

networks:
  default:
    name: hk220-network