version: '3.8'
name: sonoma

services:
  nginx:
    image: nginx:latest
    container_name: nginx-service
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
    depends_on:
      - taipy-service

  taipy-service:
    image: taipy-app
    container_name: taipy-service
    ports:
      - "5000:5000"

networks:
  default:
    name: sonoma-network